name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get IMAGE_NAME
        id: get-imagename
        run: |
          # image 名として GitHub の branch または tag 名を付与
          IMAGE_NAME=$(echo "${{ github.ref }}" | sed -e 's|.*/\(.*\)|\1|')
          # PullRequest の場合 head branch 名を利用
          [[ -n "${{ github.head_ref }}" ]] && IMAGE_NAME=${{ github.head_ref }}
          # tag push でない場合、suffix に commit sha を付与
          [[ ! "${{ github.ref }}" == "refs/tags/"* ]] && IMAGE_NAME=${IMAGE_NAME}-${{ github.sha }}

          echo "::set-output name=IMAGE_NAME::${IMAGE_NAME}"

      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ steps.get-imagename.outputs.IS_TAG != 'true' }}
        with:
          push: true
          tags: kanatakita/reviewapp-operator-demo-app:latest,kanatakita/reviewapp-operator-demo-app:${{ steps.get-imagename.outputs.IMAGE_NAME }}
